### ISSUE TITLE
Could not compile dependency :fs error

### ISSUE THREAD

**Issue by jmcaffee** [elixirkoans/elixir-koans#172]
After running `mix deps.get` successfully, running `mix meditate` results in the following error:

```
===> Compiling fs
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
** (Mix) Could not compile dependency :fs, "/home/jeff/.mix/rebar3 bare compile --paths "/home/jeff/projects/elixir/elixir-koans/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile fs", update it with "mix deps.update fs" or clean it with "mix deps.clean fs"
```

`rebar3 report "mix meditate"`:

```
Rebar3 report
 version 3.3.5+build.3719.ref4725d36
 generated at 2017-02-16T15:47:48+00:00
=================
Please submit this along with your issue at https://github.com/erlang/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: mix
Entered as:
  mix meditate
-----------------
Operating System: x86_64-unknown-linux-gnu
ERTS: Erlang/OTP 19 [erts-8.2.2] [source-1ca84a4] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false]
Root Directory: /usr/lib/erlang
Library directory: /usr/lib/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.3.0
certifi: 0.4.0
cf: 0.2.2
common_test: 1.13
compiler: 7.0.3
crypto: 3.7.2
cth_readable: 1.2.3
dialyzer: 3.0.3
edoc: 0.8.1
erlware_commons: 1.0.0
eunit: 2.3.2
eunit_formatters: 0.3.1
getopt: 0.8.2
inets: 6.3.5
kernel: 5.1.1
providers: 1.6.0
public_key: 1.3
relx: 3.22.2
sasl: 3.0.2
snmp: 5.2.4
ssl_verify_fun: 1.1.1
stdlib: 3.2
syntax_tools: 2.1.1
tools: 2.9

-----------------
Escript path: undefined
Providers:
  app_discovery as clean compile compile cover ct deps dialyzer do edoc escriptize eunit get-deps help install install_deps list lock new path pkgs release relup report shell state tar tree unlock update upgrade upgrade upgrade version xref
```

Results of `DEBUG=1 mix meditate`:

[Pastebin of stacktrace](https://pastebin.com/CP0rCmZg)

System: 
Ubuntu 16.04.2
4.4.0-62-generic

Let me know if I can provide any other info...

**Comment by awochna** [comment]
I'm encountering the same issue, also on Ubuntu 16.04

**Comment by felipesere** [comment]
I have just installed Ubuntu 16.04 a Elixir 1.4.0 (from asdf) and I can confirm that it does not reload 😢 

I'll have to look into it. Thanks for reporting! Stay tuned.

**Comment by felipesere** [comment]
I've just bumped the version exfswatch to 0.3.2 and that solved the issue on my Ubuntu Vagrant box. Do you mind pulling from master and trying again?

**Comment by jmcaffee** [comment]
The issue has been fixed in fs.

Forcing use of the latest github version solves the issue for me.

In `mix.exs`:
```
    [ { :fs,     git: "https://github.com/synrc/fs.git", override: true},
```

**Comment by awochna** [comment]
Pulling from master didn't fix the issue still. 

Explicitly telling mix to use the latest github version for `:fs` did though, thanks @jmcaffee!

I'm sure `:fs` will have a new release soon.

**Comment by felipesere** [comment]
(pressed the wrong button)

**Comment by felipesere** [comment]
@awochna and @jmcaffee could you try with latest `master`? We have updated to the latest `exfswatch` and `fs`.

**Comment by felipesere** [comment]
We are now using [file_system](https://github.com/falood/file_system), so please open a new issue if there are sill issues with Ubuntu and `mix meditate`

**Comment by mindaugaswashere** [comment]
Have you tried enter sudo ?
